# Generated by Django 4.2.3 on 2023-07-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_expense'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Expense',
        ),
    ]
